# Generated by Django 6.0.1 on 2026-01-28 07:33

import users.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.manager.UserManager()),
            ],
        ),
    ]
